url = "https://www.ziraatbank.com.tr/en/our-bank/about-us/ziraat-finans-group/domestic-subsidiaries"
output = "recursos/pages/footer-domestic-subsidiaries.html"
url = "https://www.ziraatbank.com.tr/en/our-bank/about-us/ziraat-finans-group/subsidiaries-abroad-overseas-branches-and-representative-offices"
output = "recursos/pages/footer-subsidiaries-abroad.html"
url = "https://www.ziraatbank.com.tr/en/our-bank/press-room/news-announcements"
output = "recursos/pages/footer-announcements.html"
url = "https://www.ziraatbank.com.tr/en/calculation-tools"
output = "recursos/pages/footer-calculation-tools.html"
url = "https://www.ziraatbank.com.tr/en/sitemap"
output = "recursos/pages/footer-sitemap.html"
url = "https://www.ziraatbank.com.tr/en/faq"
output = "recursos/pages/footer-faq.html"
url = "https://www.ziraatbank.com.tr/tr/bankamiz/ziraatten-duyurular/duyurular/zamanasimina-ugrayan-mevduat-ve-emanet-hesaplari"
output = "recursos/pages/footer-time-out-account.html"
url = "https://www.ziraatbank.com.tr/en/calculation-tools/iban"
output = "recursos/pages/footer-iban.html"
url = "https://www.ziraatbank.com.tr/en/legal-notice"
output = "recursos/pages/footer-legal-notice.html"
url = "https://www.ziraatbank.com.tr/en/contact-us/branches-atms"
output = "recursos/pages/footer-branches-atms.html"
url = "https://www.ziraatbank.com.tr/en/contact-us/contact-form"
output = "recursos/pages/footer-contact-form.html"
url = "https://www.ziraatbank.com.tr/en/our-bank/announcements/disclosure-of-protection-of-personal-data"
output = "recursos/pages/footer-personal-data-protection.html"
