url = "https://www.ziraatbank.com.tr/en/retail/services/western-union"
output = "recursos/pages/hero-western-union.html"
url = "https://www.ziraatbank.com.tr/en/digital-banking/mobile-banking/ziraat-mobil"
output = "recursos/pages/hero-ziraat-mobile.html"
url = "https://www.ziraatbank.com.tr/en/digital-banking/mobile-banking/ziraat-mobile-corporate"
output = "recursos/pages/hero-ziraat-mobile-corporate.html"
