url = "https://www.ziraatbank.com.tr/en/retail/accounts"
output = "recursos/pages/retail-accounts.html"
url = "https://www.ziraatbank.com.tr/en/retail/loans"
output = "recursos/pages/retail-loans.html"
url = "https://www.ziraatbank.com.tr/en/retail/cards"
output = "recursos/pages/retail-cards.html"
url = "https://www.ziraatbank.com.tr/en/retail/payments"
output = "recursos/pages/retail-payments.html"
url = "https://www.ziraatbank.com.tr/en/retail/services"
output = "recursos/pages/retail-services.html"
url = "https://www.ziraatbank.com.tr/en/retail/insurance-pension"
output = "recursos/pages/retail-insurance-pension.html"
url = "https://www.ziraatbank.com.tr/en/retail/investment"
output = "recursos/pages/retail-investment.html"
url = "https://www.ziraatbank.com.tr/en/sme/accounts"
output = "recursos/pages/sme-accounts.html"
url = "https://www.ziraatbank.com.tr/en/sme/cards"
output = "recursos/pages/sme-cards.html"
url = "https://www.ziraatbank.com.tr/en/sme/loans"
output = "recursos/pages/sme-loans.html"
url = "https://www.ziraatbank.com.tr/en/sme/foreign-trade"
output = "recursos/pages/sme-foreign-trade.html"
url = "https://www.ziraatbank.com.tr/en/sme/cash-management"
output = "recursos/pages/sme-cash-management.html"
url = "https://www.ziraatbank.com.tr/en/sme/pos-services"
output = "recursos/pages/sme-pos-services.html"
url = "https://www.ziraatbank.com.tr/en/sme/investment"
output = "recursos/pages/sme-investment.html"
url = "https://www.ziraatbank.com.tr/en/sme/agriculture"
output = "recursos/pages/sme-agriculture.html"
url = "https://www.ziraatbank.com.tr/en/corporate/accounts"
output = "recursos/pages/corporate-accounts.html"
url = "https://www.ziraatbank.com.tr/en/corporate/loans"
output = "recursos/pages/corporate-loans.html"
url = "https://www.ziraatbank.com.tr/en/corporate/foreign-trade"
output = "recursos/pages/corporate-foreign-trade.html"
url = "https://www.ziraatbank.com.tr/en/corporate/cards"
output = "recursos/pages/corporate-cards.html"
url = "https://www.ziraatbank.com.tr/en/corporate/cash-management"
output = "recursos/pages/corporate-cash-management.html"
url = "https://www.ziraatbank.com.tr/en/corporate/investment"
output = "recursos/pages/corporate-investment.html"
url = "https://www.ziraatbank.com.tr/en/corporate/agriculture"
output = "recursos/pages/corporate-agriculture.html"
